# -*- coding: UTF-8 -*-
# Code automatically generated by pycrate_asn1c

from pycrate_asn1rt.utils            import *
from pycrate_asn1rt.err              import *
from pycrate_asn1rt.glob             import make_GLOBAL, GLOBAL
from pycrate_asn1rt.dictobj          import ASN1Dict
from pycrate_asn1rt.refobj           import *
from pycrate_asn1rt.setobj           import *
from pycrate_asn1rt.asnobj_basic     import *
from pycrate_asn1rt.asnobj_str       import *
from pycrate_asn1rt.asnobj_construct import *
from pycrate_asn1rt.asnobj_class     import *
from pycrate_asn1rt.asnobj_ext       import *
from pycrate_asn1rt.init             import init_modules

class E2SM_KPM_IEs:

    _name_  = 'E2SM-KPM-IEs'
    _oid_   = [1, 3, 6, 1, 4, 1, 53148, 1, 1, 2, 2]
    
    _obj_ = [
        'GlobalKPMnode-ID',
        'GlobalKPMnode-gNB-ID',
        'GlobalgNB-ID',
        'GNB-CU-UP-ID',
        'GNB-DU-ID',
        'GNB-ID-Choice',
        'GlobalKPMnode-en-gNB-ID',
        'GlobalenGNB-ID',
        'ENGNB-ID',
        'GlobalKPMnode-ng-eNB-ID',
        'GlobalngeNB-ID',
        'ENB-ID-Choice',
        'GlobalKPMnode-eNB-ID',
        'GlobalENB-ID',
        'ENB-ID',
        'NRCGI',
        'PLMN-Identity',
        'NRCellIdentity',
        'SNSSAI',
        'maxofMessageProtocolTests',
        'maxofRICstyles',
        'maxnoofQCI',
        'maxnoofQoSFlows',
        'maxnoofSliceItems',
        'maxnoofContainerListItems',
        'maxCellingNBDU',
        'maxofContainers',
        'maxPLMN',
        'RIC-Style-Type',
        'RIC-Style-Name',
        'RIC-Format-Type',
        'E2SM-KPM-EventTriggerDefinition',
        'E2SM-KPM-EventTriggerDefinition-Format1',
        'E2SM-KPM-ActionDefinition',
        'E2SM-KPM-IndicationHeader',
        'E2SM-KPM-IndicationHeader-Format1',
        'E2SM-KPM-IndicationMessage',
        'E2SM-KPM-IndicationMessage-Format1',
        'PM-Containers-List',
        'E2SM-KPM-RANfunction-Description',
        'NI-Type',
        'RAN-Container',
        'Trigger-ConditionIE-Item',
        'RT-Period-IE',
        'RANcallProcess-ID-string',
        'RANfunction-Name',
        'RIC-EventTriggerStyle-List',
        'RIC-ReportStyle-List',
        'PF-Container',
        'GNB-CU-CP-Name',
        'GNB-DU-Name',
        'GNB-CU-UP-Name',
        'ODU-PF-Container',
        'CellResourceReportListItem',
        'ServedPlmnPerCellListItem',
        'FGC-DU-PM-Container',
        'SlicePerPlmnPerCellListItem',
        'FQIPERSlicesPerPlmnPerCellListItem',
        'EPC-DU-PM-Container',
        'PerQCIReportListItem',
        'OCUCP-PF-Container',
        'OCUUP-PF-Container',
        'PF-ContainerListItem',
        'CUUPMeasurement-Container',
        'PlmnID-List',
        'FGC-CUUP-PM-Format',
        'SliceToReportListItem',
        'FQIPERSlicesPerPlmnListItem',
        'EPC-CUUP-PM-Format',
        'PerQCIReportListItemFormat',
        ]
    _type_ = [
        'GlobalKPMnode-ID',
        'GlobalKPMnode-gNB-ID',
        'GlobalgNB-ID',
        'GNB-CU-UP-ID',
        'GNB-DU-ID',
        'GNB-ID-Choice',
        'GlobalKPMnode-en-gNB-ID',
        'GlobalenGNB-ID',
        'ENGNB-ID',
        'GlobalKPMnode-ng-eNB-ID',
        'GlobalngeNB-ID',
        'ENB-ID-Choice',
        'GlobalKPMnode-eNB-ID',
        'GlobalENB-ID',
        'ENB-ID',
        'NRCGI',
        'PLMN-Identity',
        'NRCellIdentity',
        'SNSSAI',
        'RIC-Style-Type',
        'RIC-Style-Name',
        'RIC-Format-Type',
        'E2SM-KPM-EventTriggerDefinition',
        'E2SM-KPM-EventTriggerDefinition-Format1',
        'E2SM-KPM-ActionDefinition',
        'E2SM-KPM-IndicationHeader',
        'E2SM-KPM-IndicationHeader-Format1',
        'E2SM-KPM-IndicationMessage',
        'E2SM-KPM-IndicationMessage-Format1',
        'PM-Containers-List',
        'E2SM-KPM-RANfunction-Description',
        'NI-Type',
        'RAN-Container',
        'Trigger-ConditionIE-Item',
        'RT-Period-IE',
        'RANcallProcess-ID-string',
        'RANfunction-Name',
        'RIC-EventTriggerStyle-List',
        'RIC-ReportStyle-List',
        'PF-Container',
        'GNB-CU-CP-Name',
        'GNB-DU-Name',
        'GNB-CU-UP-Name',
        'ODU-PF-Container',
        'CellResourceReportListItem',
        'ServedPlmnPerCellListItem',
        'FGC-DU-PM-Container',
        'SlicePerPlmnPerCellListItem',
        'FQIPERSlicesPerPlmnPerCellListItem',
        'EPC-DU-PM-Container',
        'PerQCIReportListItem',
        'OCUCP-PF-Container',
        'OCUUP-PF-Container',
        'PF-ContainerListItem',
        'CUUPMeasurement-Container',
        'PlmnID-List',
        'FGC-CUUP-PM-Format',
        'SliceToReportListItem',
        'FQIPERSlicesPerPlmnListItem',
        'EPC-CUUP-PM-Format',
        'PerQCIReportListItemFormat',
        ]
    _set_ = [
        ]
    _val_ = [
        'maxofMessageProtocolTests',
        'maxofRICstyles',
        'maxnoofQCI',
        'maxnoofQoSFlows',
        'maxnoofSliceItems',
        'maxnoofContainerListItems',
        'maxCellingNBDU',
        'maxofContainers',
        'maxPLMN',
        ]
    _class_ = [
        ]
    _param_ = [
        ]
    
    #-----< GlobalKPMnode-ID >-----#
    GlobalKPMnode_ID = CHOICE(name='GlobalKPMnode-ID', mode=MODE_TYPE)
    _GlobalKPMnode_ID_gNB = SEQ(name='gNB', mode=MODE_TYPE, tag=(0, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('E2SM-KPM-IEs', 'GlobalKPMnode-gNB-ID')))
    _GlobalKPMnode_ID_en_gNB = SEQ(name='en-gNB', mode=MODE_TYPE, tag=(1, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('E2SM-KPM-IEs', 'GlobalKPMnode-en-gNB-ID')))
    _GlobalKPMnode_ID_ng_eNB = SEQ(name='ng-eNB', mode=MODE_TYPE, tag=(2, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('E2SM-KPM-IEs', 'GlobalKPMnode-ng-eNB-ID')))
    _GlobalKPMnode_ID_eNB = SEQ(name='eNB', mode=MODE_TYPE, tag=(3, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('E2SM-KPM-IEs', 'GlobalKPMnode-eNB-ID')))
    GlobalKPMnode_ID._cont = ASN1Dict([
        ('gNB', _GlobalKPMnode_ID_gNB),
        ('en-gNB', _GlobalKPMnode_ID_en_gNB),
        ('ng-eNB', _GlobalKPMnode_ID_ng_eNB),
        ('eNB', _GlobalKPMnode_ID_eNB),
        ])
    GlobalKPMnode_ID._ext = []
    
    #-----< GlobalKPMnode-gNB-ID >-----#
    GlobalKPMnode_gNB_ID = SEQ(name='GlobalKPMnode-gNB-ID', mode=MODE_TYPE)
    _GlobalKPMnode_gNB_ID_global_gNB_ID = SEQ(name='global-gNB-ID', mode=MODE_TYPE, tag=(0, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('E2SM-KPM-IEs', 'GlobalgNB-ID')))
    _GlobalKPMnode_gNB_ID_gNB_CU_UP_ID = INT(name='gNB-CU-UP-ID', mode=MODE_TYPE, tag=(1, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('E2SM-KPM-IEs', 'GNB-CU-UP-ID')), opt=True)
    _GlobalKPMnode_gNB_ID_gNB_DU_ID = INT(name='gNB-DU-ID', mode=MODE_TYPE, tag=(2, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('E2SM-KPM-IEs', 'GNB-DU-ID')), opt=True)
    GlobalKPMnode_gNB_ID._cont = ASN1Dict([
        ('global-gNB-ID', _GlobalKPMnode_gNB_ID_global_gNB_ID),
        ('gNB-CU-UP-ID', _GlobalKPMnode_gNB_ID_gNB_CU_UP_ID),
        ('gNB-DU-ID', _GlobalKPMnode_gNB_ID_gNB_DU_ID),
        ])
    GlobalKPMnode_gNB_ID._ext = []
    
    #-----< GlobalgNB-ID >-----#
    GlobalgNB_ID = SEQ(name='GlobalgNB-ID', mode=MODE_TYPE)
    _GlobalgNB_ID_plmn_id = OCT_STR(name='plmn-id', mode=MODE_TYPE, tag=(0, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('E2SM-KPM-IEs', 'PLMN-Identity')))
    _GlobalgNB_ID_gnb_id = CHOICE(name='gnb-id', mode=MODE_TYPE, tag=(1, TAG_CONTEXT_SPEC, TAG_EXPLICIT), typeref=ASN1RefType(('E2SM-KPM-IEs', 'GNB-ID-Choice')))
    GlobalgNB_ID._cont = ASN1Dict([
        ('plmn-id', _GlobalgNB_ID_plmn_id),
        ('gnb-id', _GlobalgNB_ID_gnb_id),
        ])
    GlobalgNB_ID._ext = []
    
    #-----< GNB-CU-UP-ID >-----#
    GNB_CU_UP_ID = INT(name='GNB-CU-UP-ID', mode=MODE_TYPE)
    GNB_CU_UP_ID._const_val = ASN1Set(rv=[], rr=[ASN1RangeInt(lb=0, ub=68719476735)], ev=None, er=[])
    
    #-----< GNB-DU-ID >-----#
    GNB_DU_ID = INT(name='GNB-DU-ID', mode=MODE_TYPE)
    GNB_DU_ID._const_val = ASN1Set(rv=[], rr=[ASN1RangeInt(lb=0, ub=68719476735)], ev=None, er=[])
    
    #-----< GNB-ID-Choice >-----#
    GNB_ID_Choice = CHOICE(name='GNB-ID-Choice', mode=MODE_TYPE)
    _GNB_ID_Choice_gnb_ID = BIT_STR(name='gnb-ID', mode=MODE_TYPE, tag=(0, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    _GNB_ID_Choice_gnb_ID._const_sz = ASN1Set(rv=[], rr=[ASN1RangeInt(lb=22, ub=32)], ev=None, er=[])
    GNB_ID_Choice._cont = ASN1Dict([
        ('gnb-ID', _GNB_ID_Choice_gnb_ID),
        ])
    GNB_ID_Choice._ext = []
    
    #-----< GlobalKPMnode-en-gNB-ID >-----#
    GlobalKPMnode_en_gNB_ID = SEQ(name='GlobalKPMnode-en-gNB-ID', mode=MODE_TYPE)
    _GlobalKPMnode_en_gNB_ID_global_gNB_ID = SEQ(name='global-gNB-ID', mode=MODE_TYPE, tag=(0, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('E2SM-KPM-IEs', 'GlobalenGNB-ID')))
    GlobalKPMnode_en_gNB_ID._cont = ASN1Dict([
        ('global-gNB-ID', _GlobalKPMnode_en_gNB_ID_global_gNB_ID),
        ])
    GlobalKPMnode_en_gNB_ID._ext = []
    
    #-----< GlobalenGNB-ID >-----#
    GlobalenGNB_ID = SEQ(name='GlobalenGNB-ID', mode=MODE_TYPE)
    _GlobalenGNB_ID_pLMN_Identity = OCT_STR(name='pLMN-Identity', mode=MODE_TYPE, tag=(0, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('E2SM-KPM-IEs', 'PLMN-Identity')))
    _GlobalenGNB_ID_gNB_ID = CHOICE(name='gNB-ID', mode=MODE_TYPE, tag=(1, TAG_CONTEXT_SPEC, TAG_EXPLICIT), typeref=ASN1RefType(('E2SM-KPM-IEs', 'ENGNB-ID')))
    GlobalenGNB_ID._cont = ASN1Dict([
        ('pLMN-Identity', _GlobalenGNB_ID_pLMN_Identity),
        ('gNB-ID', _GlobalenGNB_ID_gNB_ID),
        ])
    GlobalenGNB_ID._ext = []
    
    #-----< ENGNB-ID >-----#
    ENGNB_ID = CHOICE(name='ENGNB-ID', mode=MODE_TYPE)
    _ENGNB_ID_gNB_ID = BIT_STR(name='gNB-ID', mode=MODE_TYPE, tag=(0, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    _ENGNB_ID_gNB_ID._const_sz = ASN1Set(rv=[], rr=[ASN1RangeInt(lb=22, ub=32)], ev=None, er=[])
    ENGNB_ID._cont = ASN1Dict([
        ('gNB-ID', _ENGNB_ID_gNB_ID),
        ])
    ENGNB_ID._ext = []
    
    #-----< GlobalKPMnode-ng-eNB-ID >-----#
    GlobalKPMnode_ng_eNB_ID = SEQ(name='GlobalKPMnode-ng-eNB-ID', mode=MODE_TYPE)
    _GlobalKPMnode_ng_eNB_ID_global_ng_eNB_ID = SEQ(name='global-ng-eNB-ID', mode=MODE_TYPE, tag=(0, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('E2SM-KPM-IEs', 'GlobalngeNB-ID')))
    GlobalKPMnode_ng_eNB_ID._cont = ASN1Dict([
        ('global-ng-eNB-ID', _GlobalKPMnode_ng_eNB_ID_global_ng_eNB_ID),
        ])
    GlobalKPMnode_ng_eNB_ID._ext = []
    
    #-----< GlobalngeNB-ID >-----#
    GlobalngeNB_ID = SEQ(name='GlobalngeNB-ID', mode=MODE_TYPE)
    _GlobalngeNB_ID_plmn_id = OCT_STR(name='plmn-id', mode=MODE_TYPE, tag=(0, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('E2SM-KPM-IEs', 'PLMN-Identity')))
    _GlobalngeNB_ID_enb_id = CHOICE(name='enb-id', mode=MODE_TYPE, tag=(1, TAG_CONTEXT_SPEC, TAG_EXPLICIT), typeref=ASN1RefType(('E2SM-KPM-IEs', 'ENB-ID-Choice')))
    GlobalngeNB_ID._cont = ASN1Dict([
        ('plmn-id', _GlobalngeNB_ID_plmn_id),
        ('enb-id', _GlobalngeNB_ID_enb_id),
        ])
    GlobalngeNB_ID._ext = []
    
    #-----< ENB-ID-Choice >-----#
    ENB_ID_Choice = CHOICE(name='ENB-ID-Choice', mode=MODE_TYPE)
    _ENB_ID_Choice_enb_ID_macro = BIT_STR(name='enb-ID-macro', mode=MODE_TYPE, tag=(0, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    _ENB_ID_Choice_enb_ID_macro._const_sz = ASN1Set(rv=[20], rr=[], ev=None, er=[])
    _ENB_ID_Choice_enb_ID_shortmacro = BIT_STR(name='enb-ID-shortmacro', mode=MODE_TYPE, tag=(1, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    _ENB_ID_Choice_enb_ID_shortmacro._const_sz = ASN1Set(rv=[18], rr=[], ev=None, er=[])
    _ENB_ID_Choice_enb_ID_longmacro = BIT_STR(name='enb-ID-longmacro', mode=MODE_TYPE, tag=(2, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    _ENB_ID_Choice_enb_ID_longmacro._const_sz = ASN1Set(rv=[21], rr=[], ev=None, er=[])
    ENB_ID_Choice._cont = ASN1Dict([
        ('enb-ID-macro', _ENB_ID_Choice_enb_ID_macro),
        ('enb-ID-shortmacro', _ENB_ID_Choice_enb_ID_shortmacro),
        ('enb-ID-longmacro', _ENB_ID_Choice_enb_ID_longmacro),
        ])
    ENB_ID_Choice._ext = []
    
    #-----< GlobalKPMnode-eNB-ID >-----#
    GlobalKPMnode_eNB_ID = SEQ(name='GlobalKPMnode-eNB-ID', mode=MODE_TYPE)
    _GlobalKPMnode_eNB_ID_global_eNB_ID = SEQ(name='global-eNB-ID', mode=MODE_TYPE, tag=(0, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('E2SM-KPM-IEs', 'GlobalENB-ID')))
    GlobalKPMnode_eNB_ID._cont = ASN1Dict([
        ('global-eNB-ID', _GlobalKPMnode_eNB_ID_global_eNB_ID),
        ])
    GlobalKPMnode_eNB_ID._ext = []
    
    #-----< GlobalENB-ID >-----#
    GlobalENB_ID = SEQ(name='GlobalENB-ID', mode=MODE_TYPE)
    _GlobalENB_ID_pLMN_Identity = OCT_STR(name='pLMN-Identity', mode=MODE_TYPE, tag=(0, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('E2SM-KPM-IEs', 'PLMN-Identity')))
    _GlobalENB_ID_eNB_ID = CHOICE(name='eNB-ID', mode=MODE_TYPE, tag=(1, TAG_CONTEXT_SPEC, TAG_EXPLICIT), typeref=ASN1RefType(('E2SM-KPM-IEs', 'ENB-ID')))
    GlobalENB_ID._cont = ASN1Dict([
        ('pLMN-Identity', _GlobalENB_ID_pLMN_Identity),
        ('eNB-ID', _GlobalENB_ID_eNB_ID),
        ])
    GlobalENB_ID._ext = []
    
    #-----< ENB-ID >-----#
    ENB_ID = CHOICE(name='ENB-ID', mode=MODE_TYPE)
    _ENB_ID_macro_eNB_ID = BIT_STR(name='macro-eNB-ID', mode=MODE_TYPE, tag=(0, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    _ENB_ID_macro_eNB_ID._const_sz = ASN1Set(rv=[20], rr=[], ev=None, er=[])
    _ENB_ID_home_eNB_ID = BIT_STR(name='home-eNB-ID', mode=MODE_TYPE, tag=(1, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    _ENB_ID_home_eNB_ID._const_sz = ASN1Set(rv=[28], rr=[], ev=None, er=[])
    _ENB_ID_short_Macro_eNB_ID = BIT_STR(name='short-Macro-eNB-ID', mode=MODE_TYPE, tag=(2, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    _ENB_ID_short_Macro_eNB_ID._const_sz = ASN1Set(rv=[18], rr=[], ev=None, er=[])
    _ENB_ID_long_Macro_eNB_ID = BIT_STR(name='long-Macro-eNB-ID', mode=MODE_TYPE, tag=(3, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    _ENB_ID_long_Macro_eNB_ID._const_sz = ASN1Set(rv=[21], rr=[], ev=None, er=[])
    ENB_ID._cont = ASN1Dict([
        ('macro-eNB-ID', _ENB_ID_macro_eNB_ID),
        ('home-eNB-ID', _ENB_ID_home_eNB_ID),
        ('short-Macro-eNB-ID', _ENB_ID_short_Macro_eNB_ID),
        ('long-Macro-eNB-ID', _ENB_ID_long_Macro_eNB_ID),
        ])
    ENB_ID._ext = ['short-Macro-eNB-ID', 'long-Macro-eNB-ID']
    
    #-----< NRCGI >-----#
    NRCGI = SEQ(name='NRCGI', mode=MODE_TYPE)
    _NRCGI_pLMN_Identity = OCT_STR(name='pLMN-Identity', mode=MODE_TYPE, tag=(0, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('E2SM-KPM-IEs', 'PLMN-Identity')))
    _NRCGI_nRCellIdentity = BIT_STR(name='nRCellIdentity', mode=MODE_TYPE, tag=(1, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('E2SM-KPM-IEs', 'NRCellIdentity')))
    NRCGI._cont = ASN1Dict([
        ('pLMN-Identity', _NRCGI_pLMN_Identity),
        ('nRCellIdentity', _NRCGI_nRCellIdentity),
        ])
    NRCGI._ext = None
    
    #-----< PLMN-Identity >-----#
    PLMN_Identity = OCT_STR(name='PLMN-Identity', mode=MODE_TYPE)
    PLMN_Identity._const_sz = ASN1Set(rv=[3], rr=[], ev=None, er=[])
    
    #-----< NRCellIdentity >-----#
    NRCellIdentity = BIT_STR(name='NRCellIdentity', mode=MODE_TYPE)
    NRCellIdentity._const_sz = ASN1Set(rv=[36], rr=[], ev=None, er=[])
    
    #-----< SNSSAI >-----#
    SNSSAI = SEQ(name='SNSSAI', mode=MODE_TYPE)
    _SNSSAI_sST = OCT_STR(name='sST', mode=MODE_TYPE, tag=(0, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    _SNSSAI_sST._const_sz = ASN1Set(rv=[1], rr=[], ev=None, er=[])
    _SNSSAI_sD = OCT_STR(name='sD', mode=MODE_TYPE, tag=(1, TAG_CONTEXT_SPEC, TAG_IMPLICIT), opt=True)
    _SNSSAI_sD._const_sz = ASN1Set(rv=[3], rr=[], ev=None, er=[])
    SNSSAI._cont = ASN1Dict([
        ('sST', _SNSSAI_sST),
        ('sD', _SNSSAI_sD),
        ])
    SNSSAI._ext = None
    
    #-----< maxofMessageProtocolTests >-----#
    maxofMessageProtocolTests = INT(name='maxofMessageProtocolTests', mode=MODE_VALUE)
    maxofMessageProtocolTests._val = 15
    
    #-----< maxofRICstyles >-----#
    maxofRICstyles = INT(name='maxofRICstyles', mode=MODE_VALUE)
    maxofRICstyles._val = 63
    
    #-----< maxnoofQCI >-----#
    maxnoofQCI = INT(name='maxnoofQCI', mode=MODE_VALUE)
    maxnoofQCI._val = 256
    
    #-----< maxnoofQoSFlows >-----#
    maxnoofQoSFlows = INT(name='maxnoofQoSFlows', mode=MODE_VALUE)
    maxnoofQoSFlows._val = 64
    
    #-----< maxnoofSliceItems >-----#
    maxnoofSliceItems = INT(name='maxnoofSliceItems', mode=MODE_VALUE)
    maxnoofSliceItems._val = 1024
    
    #-----< maxnoofContainerListItems >-----#
    maxnoofContainerListItems = INT(name='maxnoofContainerListItems', mode=MODE_VALUE)
    maxnoofContainerListItems._val = 3
    
    #-----< maxCellingNBDU >-----#
    maxCellingNBDU = INT(name='maxCellingNBDU', mode=MODE_VALUE)
    maxCellingNBDU._val = 512
    
    #-----< maxofContainers >-----#
    maxofContainers = INT(name='maxofContainers', mode=MODE_VALUE)
    maxofContainers._val = 8
    
    #-----< maxPLMN >-----#
    maxPLMN = INT(name='maxPLMN', mode=MODE_VALUE)
    maxPLMN._val = 12
    
    #-----< RIC-Style-Type >-----#
    RIC_Style_Type = INT(name='RIC-Style-Type', mode=MODE_TYPE)
    
    #-----< RIC-Style-Name >-----#
    RIC_Style_Name = STR_PRINT(name='RIC-Style-Name', mode=MODE_TYPE)
    RIC_Style_Name._const_sz = ASN1Set(rv=[], rr=[ASN1RangeInt(lb=1, ub=150)], ev=[], er=[])
    
    #-----< RIC-Format-Type >-----#
    RIC_Format_Type = INT(name='RIC-Format-Type', mode=MODE_TYPE)
    
    #-----< E2SM-KPM-EventTriggerDefinition >-----#
    E2SM_KPM_EventTriggerDefinition = CHOICE(name='E2SM-KPM-EventTriggerDefinition', mode=MODE_TYPE)
    _E2SM_KPM_EventTriggerDefinition_eventDefinition_Format1 = SEQ(name='eventDefinition-Format1', mode=MODE_TYPE, tag=(0, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('E2SM-KPM-IEs', 'E2SM-KPM-EventTriggerDefinition-Format1')))
    E2SM_KPM_EventTriggerDefinition._cont = ASN1Dict([
        ('eventDefinition-Format1', _E2SM_KPM_EventTriggerDefinition_eventDefinition_Format1),
        ])
    E2SM_KPM_EventTriggerDefinition._ext = []
    
    #-----< E2SM-KPM-EventTriggerDefinition-Format1 >-----#
    E2SM_KPM_EventTriggerDefinition_Format1 = SEQ(name='E2SM-KPM-EventTriggerDefinition-Format1', mode=MODE_TYPE)
    _E2SM_KPM_EventTriggerDefinition_Format1_policyTest_List = SEQ_OF(name='policyTest-List', mode=MODE_TYPE, tag=(0, TAG_CONTEXT_SPEC, TAG_IMPLICIT), opt=True)
    __E2SM_KPM_EventTriggerDefinition_Format1_policyTest_List__item_ = SEQ(name='_item_', mode=MODE_TYPE, typeref=ASN1RefType(('E2SM-KPM-IEs', 'Trigger-ConditionIE-Item')))
    _E2SM_KPM_EventTriggerDefinition_Format1_policyTest_List._cont = __E2SM_KPM_EventTriggerDefinition_Format1_policyTest_List__item_
    _E2SM_KPM_EventTriggerDefinition_Format1_policyTest_List._const_sz = ASN1Set(rv=[], rr=[ASN1RangeInt(lb=1, ub=15)], ev=None, er=[])
    E2SM_KPM_EventTriggerDefinition_Format1._cont = ASN1Dict([
        ('policyTest-List', _E2SM_KPM_EventTriggerDefinition_Format1_policyTest_List),
        ])
    E2SM_KPM_EventTriggerDefinition_Format1._ext = []
    
    #-----< E2SM-KPM-ActionDefinition >-----#
    E2SM_KPM_ActionDefinition = SEQ(name='E2SM-KPM-ActionDefinition', mode=MODE_TYPE)
    _E2SM_KPM_ActionDefinition_ric_Style_Type = INT(name='ric-Style-Type', mode=MODE_TYPE, tag=(0, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('E2SM-KPM-IEs', 'RIC-Style-Type')))
    E2SM_KPM_ActionDefinition._cont = ASN1Dict([
        ('ric-Style-Type', _E2SM_KPM_ActionDefinition_ric_Style_Type),
        ])
    E2SM_KPM_ActionDefinition._ext = []
    
    #-----< E2SM-KPM-IndicationHeader >-----#
    E2SM_KPM_IndicationHeader = CHOICE(name='E2SM-KPM-IndicationHeader', mode=MODE_TYPE)
    _E2SM_KPM_IndicationHeader_indicationHeader_Format1 = SEQ(name='indicationHeader-Format1', mode=MODE_TYPE, tag=(0, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('E2SM-KPM-IEs', 'E2SM-KPM-IndicationHeader-Format1')))
    E2SM_KPM_IndicationHeader._cont = ASN1Dict([
        ('indicationHeader-Format1', _E2SM_KPM_IndicationHeader_indicationHeader_Format1),
        ])
    E2SM_KPM_IndicationHeader._ext = []
    
    #-----< E2SM-KPM-IndicationHeader-Format1 >-----#
    E2SM_KPM_IndicationHeader_Format1 = SEQ(name='E2SM-KPM-IndicationHeader-Format1', mode=MODE_TYPE)
    _E2SM_KPM_IndicationHeader_Format1_id_GlobalKPMnode_ID = CHOICE(name='id-GlobalKPMnode-ID', mode=MODE_TYPE, tag=(0, TAG_CONTEXT_SPEC, TAG_EXPLICIT), typeref=ASN1RefType(('E2SM-KPM-IEs', 'GlobalKPMnode-ID')), opt=True)
    _E2SM_KPM_IndicationHeader_Format1_nRCGI = SEQ(name='nRCGI', mode=MODE_TYPE, tag=(1, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('E2SM-KPM-IEs', 'NRCGI')), opt=True)
    _E2SM_KPM_IndicationHeader_Format1_pLMN_Identity = OCT_STR(name='pLMN-Identity', mode=MODE_TYPE, tag=(2, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('E2SM-KPM-IEs', 'PLMN-Identity')), opt=True)
    _E2SM_KPM_IndicationHeader_Format1_sliceID = SEQ(name='sliceID', mode=MODE_TYPE, tag=(3, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('E2SM-KPM-IEs', 'SNSSAI')), opt=True)
    _E2SM_KPM_IndicationHeader_Format1_fiveQI = INT(name='fiveQI', mode=MODE_TYPE, tag=(4, TAG_CONTEXT_SPEC, TAG_IMPLICIT), opt=True)
    _E2SM_KPM_IndicationHeader_Format1_fiveQI._const_val = ASN1Set(rv=[], rr=[ASN1RangeInt(lb=0, ub=255)], ev=None, er=[])
    _E2SM_KPM_IndicationHeader_Format1_qci = INT(name='qci', mode=MODE_TYPE, tag=(5, TAG_CONTEXT_SPEC, TAG_IMPLICIT), opt=True)
    _E2SM_KPM_IndicationHeader_Format1_qci._const_val = ASN1Set(rv=[], rr=[ASN1RangeInt(lb=0, ub=255)], ev=None, er=[])
    E2SM_KPM_IndicationHeader_Format1._cont = ASN1Dict([
        ('id-GlobalKPMnode-ID', _E2SM_KPM_IndicationHeader_Format1_id_GlobalKPMnode_ID),
        ('nRCGI', _E2SM_KPM_IndicationHeader_Format1_nRCGI),
        ('pLMN-Identity', _E2SM_KPM_IndicationHeader_Format1_pLMN_Identity),
        ('sliceID', _E2SM_KPM_IndicationHeader_Format1_sliceID),
        ('fiveQI', _E2SM_KPM_IndicationHeader_Format1_fiveQI),
        ('qci', _E2SM_KPM_IndicationHeader_Format1_qci),
        ])
    E2SM_KPM_IndicationHeader_Format1._ext = []
    
    #-----< E2SM-KPM-IndicationMessage >-----#
    E2SM_KPM_IndicationMessage = CHOICE(name='E2SM-KPM-IndicationMessage', mode=MODE_TYPE)
    _E2SM_KPM_IndicationMessage_ric_Style_Type = INT(name='ric-Style-Type', mode=MODE_TYPE, tag=(0, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('E2SM-KPM-IEs', 'RIC-Style-Type')))
    _E2SM_KPM_IndicationMessage_indicationMessage_Format1 = SEQ(name='indicationMessage-Format1', mode=MODE_TYPE, tag=(1, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('E2SM-KPM-IEs', 'E2SM-KPM-IndicationMessage-Format1')))
    E2SM_KPM_IndicationMessage._cont = ASN1Dict([
        ('ric-Style-Type', _E2SM_KPM_IndicationMessage_ric_Style_Type),
        ('indicationMessage-Format1', _E2SM_KPM_IndicationMessage_indicationMessage_Format1),
        ])
    E2SM_KPM_IndicationMessage._ext = []
    
    #-----< E2SM-KPM-IndicationMessage-Format1 >-----#
    E2SM_KPM_IndicationMessage_Format1 = SEQ(name='E2SM-KPM-IndicationMessage-Format1', mode=MODE_TYPE)
    _E2SM_KPM_IndicationMessage_Format1_pm_Containers = SEQ_OF(name='pm-Containers', mode=MODE_TYPE, tag=(0, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    __E2SM_KPM_IndicationMessage_Format1_pm_Containers__item_ = SEQ(name='_item_', mode=MODE_TYPE, typeref=ASN1RefType(('E2SM-KPM-IEs', 'PM-Containers-List')))
    _E2SM_KPM_IndicationMessage_Format1_pm_Containers._cont = __E2SM_KPM_IndicationMessage_Format1_pm_Containers__item_
    _E2SM_KPM_IndicationMessage_Format1_pm_Containers._const_sz = ASN1Set(rv=[], rr=[ASN1RangeInt(lb=1, ub=512)], ev=None, er=[])
    E2SM_KPM_IndicationMessage_Format1._cont = ASN1Dict([
        ('pm-Containers', _E2SM_KPM_IndicationMessage_Format1_pm_Containers),
        ])
    E2SM_KPM_IndicationMessage_Format1._ext = []
    
    #-----< PM-Containers-List >-----#
    PM_Containers_List = SEQ(name='PM-Containers-List', mode=MODE_TYPE)
    _PM_Containers_List_performanceContainer = CHOICE(name='performanceContainer', mode=MODE_TYPE, tag=(0, TAG_CONTEXT_SPEC, TAG_EXPLICIT), typeref=ASN1RefType(('E2SM-KPM-IEs', 'PF-Container')), opt=True)
    _PM_Containers_List_theRANContainer = OCT_STR(name='theRANContainer', mode=MODE_TYPE, tag=(1, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('E2SM-KPM-IEs', 'RAN-Container')), opt=True)
    PM_Containers_List._cont = ASN1Dict([
        ('performanceContainer', _PM_Containers_List_performanceContainer),
        ('theRANContainer', _PM_Containers_List_theRANContainer),
        ])
    PM_Containers_List._ext = []
    
    #-----< E2SM-KPM-RANfunction-Description >-----#
    E2SM_KPM_RANfunction_Description = SEQ(name='E2SM-KPM-RANfunction-Description', mode=MODE_TYPE)
    _E2SM_KPM_RANfunction_Description_ranFunction_Name = SEQ(name='ranFunction-Name', mode=MODE_TYPE, tag=(0, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('E2SM-KPM-IEs', 'RANfunction-Name')))
    _E2SM_KPM_RANfunction_Description_e2SM_KPM_RANfunction_Item = SEQ(name='e2SM-KPM-RANfunction-Item', mode=MODE_TYPE, tag=(1, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    __E2SM_KPM_RANfunction_Description_e2SM_KPM_RANfunction_Item_ric_EventTriggerStyle_List = SEQ_OF(name='ric-EventTriggerStyle-List', mode=MODE_TYPE, tag=(0, TAG_CONTEXT_SPEC, TAG_IMPLICIT), opt=True)
    ___E2SM_KPM_RANfunction_Description_e2SM_KPM_RANfunction_Item_ric_EventTriggerStyle_List__item_ = SEQ(name='_item_', mode=MODE_TYPE, typeref=ASN1RefType(('E2SM-KPM-IEs', 'RIC-EventTriggerStyle-List')))
    __E2SM_KPM_RANfunction_Description_e2SM_KPM_RANfunction_Item_ric_EventTriggerStyle_List._cont = ___E2SM_KPM_RANfunction_Description_e2SM_KPM_RANfunction_Item_ric_EventTriggerStyle_List__item_
    __E2SM_KPM_RANfunction_Description_e2SM_KPM_RANfunction_Item_ric_EventTriggerStyle_List._const_sz = ASN1Set(rv=[], rr=[ASN1RangeInt(lb=1, ub=63)], ev=None, er=[])
    __E2SM_KPM_RANfunction_Description_e2SM_KPM_RANfunction_Item_ric_ReportStyle_List = SEQ_OF(name='ric-ReportStyle-List', mode=MODE_TYPE, tag=(1, TAG_CONTEXT_SPEC, TAG_IMPLICIT), opt=True)
    ___E2SM_KPM_RANfunction_Description_e2SM_KPM_RANfunction_Item_ric_ReportStyle_List__item_ = SEQ(name='_item_', mode=MODE_TYPE, typeref=ASN1RefType(('E2SM-KPM-IEs', 'RIC-ReportStyle-List')))
    __E2SM_KPM_RANfunction_Description_e2SM_KPM_RANfunction_Item_ric_ReportStyle_List._cont = ___E2SM_KPM_RANfunction_Description_e2SM_KPM_RANfunction_Item_ric_ReportStyle_List__item_
    __E2SM_KPM_RANfunction_Description_e2SM_KPM_RANfunction_Item_ric_ReportStyle_List._const_sz = ASN1Set(rv=[], rr=[ASN1RangeInt(lb=1, ub=63)], ev=None, er=[])
    _E2SM_KPM_RANfunction_Description_e2SM_KPM_RANfunction_Item._cont = ASN1Dict([
        ('ric-EventTriggerStyle-List', __E2SM_KPM_RANfunction_Description_e2SM_KPM_RANfunction_Item_ric_EventTriggerStyle_List),
        ('ric-ReportStyle-List', __E2SM_KPM_RANfunction_Description_e2SM_KPM_RANfunction_Item_ric_ReportStyle_List),
        ])
    _E2SM_KPM_RANfunction_Description_e2SM_KPM_RANfunction_Item._ext = []
    E2SM_KPM_RANfunction_Description._cont = ASN1Dict([
        ('ranFunction-Name', _E2SM_KPM_RANfunction_Description_ranFunction_Name),
        ('e2SM-KPM-RANfunction-Item', _E2SM_KPM_RANfunction_Description_e2SM_KPM_RANfunction_Item),
        ])
    E2SM_KPM_RANfunction_Description._ext = []
    
    #-----< NI-Type >-----#
    NI_Type = ENUM(name='NI-Type', mode=MODE_TYPE)
    NI_Type._cont = ASN1Dict([('x2-u', 0), ('xn-u', 1), ('f1-u', 2)])
    NI_Type._ext = []
    
    #-----< RAN-Container >-----#
    RAN_Container = OCT_STR(name='RAN-Container', mode=MODE_TYPE)
    
    #-----< Trigger-ConditionIE-Item >-----#
    Trigger_ConditionIE_Item = SEQ(name='Trigger-ConditionIE-Item', mode=MODE_TYPE)
    _Trigger_ConditionIE_Item_report_Period_IE = ENUM(name='report-Period-IE', mode=MODE_TYPE, tag=(0, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('E2SM-KPM-IEs', 'RT-Period-IE')))
    Trigger_ConditionIE_Item._cont = ASN1Dict([
        ('report-Period-IE', _Trigger_ConditionIE_Item_report_Period_IE),
        ])
    Trigger_ConditionIE_Item._ext = []
    
    #-----< RT-Period-IE >-----#
    RT_Period_IE = ENUM(name='RT-Period-IE', mode=MODE_TYPE)
    RT_Period_IE._cont = ASN1Dict([('ms10', 0), ('ms20', 1), ('ms32', 2), ('ms40', 3), ('ms60', 4), ('ms64', 5), ('ms70', 6), ('ms80', 7), ('ms128', 8), ('ms160', 9), ('ms256', 10), ('ms320', 11), ('ms512', 12), ('ms640', 13), ('ms1024', 14), ('ms1280', 15), ('ms2048', 16), ('ms2560', 17), ('ms5120', 18), ('ms10240', 19)])
    RT_Period_IE._ext = []
    
    #-----< RANcallProcess-ID-string >-----#
    RANcallProcess_ID_string = STR_PRINT(name='RANcallProcess-ID-string', mode=MODE_TYPE)
    RANcallProcess_ID_string._const_sz = ASN1Set(rv=[], rr=[ASN1RangeInt(lb=1, ub=150)], ev=[], er=[])
    
    #-----< RANfunction-Name >-----#
    RANfunction_Name = SEQ(name='RANfunction-Name', mode=MODE_TYPE)
    _RANfunction_Name_ranFunction_ShortName = STR_PRINT(name='ranFunction-ShortName', mode=MODE_TYPE, tag=(0, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    _RANfunction_Name_ranFunction_ShortName._const_sz = ASN1Set(rv=[], rr=[ASN1RangeInt(lb=1, ub=150)], ev=[], er=[])
    _RANfunction_Name_ranFunction_E2SM_OID = STR_PRINT(name='ranFunction-E2SM-OID', mode=MODE_TYPE, tag=(1, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    _RANfunction_Name_ranFunction_E2SM_OID._const_sz = ASN1Set(rv=[], rr=[ASN1RangeInt(lb=1, ub=1000)], ev=[], er=[])
    _RANfunction_Name_ranFunction_Description = STR_PRINT(name='ranFunction-Description', mode=MODE_TYPE, tag=(2, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    _RANfunction_Name_ranFunction_Description._const_sz = ASN1Set(rv=[], rr=[ASN1RangeInt(lb=1, ub=150)], ev=[], er=[])
    _RANfunction_Name_ranFunction_Instance = INT(name='ranFunction-Instance', mode=MODE_TYPE, tag=(3, TAG_CONTEXT_SPEC, TAG_IMPLICIT), opt=True)
    RANfunction_Name._cont = ASN1Dict([
        ('ranFunction-ShortName', _RANfunction_Name_ranFunction_ShortName),
        ('ranFunction-E2SM-OID', _RANfunction_Name_ranFunction_E2SM_OID),
        ('ranFunction-Description', _RANfunction_Name_ranFunction_Description),
        ('ranFunction-Instance', _RANfunction_Name_ranFunction_Instance),
        ])
    RANfunction_Name._ext = []
    
    #-----< RIC-EventTriggerStyle-List >-----#
    RIC_EventTriggerStyle_List = SEQ(name='RIC-EventTriggerStyle-List', mode=MODE_TYPE)
    _RIC_EventTriggerStyle_List_ric_EventTriggerStyle_Type = INT(name='ric-EventTriggerStyle-Type', mode=MODE_TYPE, tag=(0, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('E2SM-KPM-IEs', 'RIC-Style-Type')))
    _RIC_EventTriggerStyle_List_ric_EventTriggerStyle_Name = STR_PRINT(name='ric-EventTriggerStyle-Name', mode=MODE_TYPE, tag=(1, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('E2SM-KPM-IEs', 'RIC-Style-Name')))
    _RIC_EventTriggerStyle_List_ric_EventTriggerFormat_Type = INT(name='ric-EventTriggerFormat-Type', mode=MODE_TYPE, tag=(2, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('E2SM-KPM-IEs', 'RIC-Format-Type')))
    RIC_EventTriggerStyle_List._cont = ASN1Dict([
        ('ric-EventTriggerStyle-Type', _RIC_EventTriggerStyle_List_ric_EventTriggerStyle_Type),
        ('ric-EventTriggerStyle-Name', _RIC_EventTriggerStyle_List_ric_EventTriggerStyle_Name),
        ('ric-EventTriggerFormat-Type', _RIC_EventTriggerStyle_List_ric_EventTriggerFormat_Type),
        ])
    RIC_EventTriggerStyle_List._ext = []
    
    #-----< RIC-ReportStyle-List >-----#
    RIC_ReportStyle_List = SEQ(name='RIC-ReportStyle-List', mode=MODE_TYPE)
    _RIC_ReportStyle_List_ric_ReportStyle_Type = INT(name='ric-ReportStyle-Type', mode=MODE_TYPE, tag=(0, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('E2SM-KPM-IEs', 'RIC-Style-Type')))
    _RIC_ReportStyle_List_ric_ReportStyle_Name = STR_PRINT(name='ric-ReportStyle-Name', mode=MODE_TYPE, tag=(1, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('E2SM-KPM-IEs', 'RIC-Style-Name')))
    _RIC_ReportStyle_List_ric_IndicationHeaderFormat_Type = INT(name='ric-IndicationHeaderFormat-Type', mode=MODE_TYPE, tag=(2, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('E2SM-KPM-IEs', 'RIC-Format-Type')))
    _RIC_ReportStyle_List_ric_IndicationMessageFormat_Type = INT(name='ric-IndicationMessageFormat-Type', mode=MODE_TYPE, tag=(3, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('E2SM-KPM-IEs', 'RIC-Format-Type')))
    RIC_ReportStyle_List._cont = ASN1Dict([
        ('ric-ReportStyle-Type', _RIC_ReportStyle_List_ric_ReportStyle_Type),
        ('ric-ReportStyle-Name', _RIC_ReportStyle_List_ric_ReportStyle_Name),
        ('ric-IndicationHeaderFormat-Type', _RIC_ReportStyle_List_ric_IndicationHeaderFormat_Type),
        ('ric-IndicationMessageFormat-Type', _RIC_ReportStyle_List_ric_IndicationMessageFormat_Type),
        ])
    RIC_ReportStyle_List._ext = []
    
    #-----< PF-Container >-----#
    PF_Container = CHOICE(name='PF-Container', mode=MODE_TYPE)
    _PF_Container_oDU = SEQ(name='oDU', mode=MODE_TYPE, tag=(0, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('E2SM-KPM-IEs', 'ODU-PF-Container')))
    _PF_Container_oCU_CP = SEQ(name='oCU-CP', mode=MODE_TYPE, tag=(1, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('E2SM-KPM-IEs', 'OCUCP-PF-Container')))
    _PF_Container_oCU_UP = SEQ(name='oCU-UP', mode=MODE_TYPE, tag=(2, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('E2SM-KPM-IEs', 'OCUUP-PF-Container')))
    PF_Container._cont = ASN1Dict([
        ('oDU', _PF_Container_oDU),
        ('oCU-CP', _PF_Container_oCU_CP),
        ('oCU-UP', _PF_Container_oCU_UP),
        ])
    PF_Container._ext = None
    
    #-----< GNB-CU-CP-Name >-----#
    GNB_CU_CP_Name = STR_PRINT(name='GNB-CU-CP-Name', mode=MODE_TYPE)
    GNB_CU_CP_Name._const_sz = ASN1Set(rv=[], rr=[ASN1RangeInt(lb=1, ub=150)], ev=[], er=[])
    
    #-----< GNB-DU-Name >-----#
    GNB_DU_Name = STR_PRINT(name='GNB-DU-Name', mode=MODE_TYPE)
    GNB_DU_Name._const_sz = ASN1Set(rv=[], rr=[ASN1RangeInt(lb=1, ub=150)], ev=[], er=[])
    
    #-----< GNB-CU-UP-Name >-----#
    GNB_CU_UP_Name = STR_PRINT(name='GNB-CU-UP-Name', mode=MODE_TYPE)
    GNB_CU_UP_Name._const_sz = ASN1Set(rv=[], rr=[ASN1RangeInt(lb=1, ub=150)], ev=[], er=[])
    
    #-----< ODU-PF-Container >-----#
    ODU_PF_Container = SEQ(name='ODU-PF-Container', mode=MODE_TYPE)
    _ODU_PF_Container_cellResourceReportList = SEQ_OF(name='cellResourceReportList', mode=MODE_TYPE, tag=(0, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    __ODU_PF_Container_cellResourceReportList__item_ = SEQ(name='_item_', mode=MODE_TYPE, typeref=ASN1RefType(('E2SM-KPM-IEs', 'CellResourceReportListItem')))
    _ODU_PF_Container_cellResourceReportList._cont = __ODU_PF_Container_cellResourceReportList__item_
    _ODU_PF_Container_cellResourceReportList._const_sz = ASN1Set(rv=[], rr=[ASN1RangeInt(lb=1, ub=512)], ev=None, er=[])
    ODU_PF_Container._cont = ASN1Dict([
        ('cellResourceReportList', _ODU_PF_Container_cellResourceReportList),
        ])
    ODU_PF_Container._ext = []
    
    #-----< CellResourceReportListItem >-----#
    CellResourceReportListItem = SEQ(name='CellResourceReportListItem', mode=MODE_TYPE)
    _CellResourceReportListItem_nRCGI = SEQ(name='nRCGI', mode=MODE_TYPE, tag=(0, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('E2SM-KPM-IEs', 'NRCGI')))
    _CellResourceReportListItem_dl_TotalofAvailablePRBs = INT(name='dl-TotalofAvailablePRBs', mode=MODE_TYPE, tag=(1, TAG_CONTEXT_SPEC, TAG_IMPLICIT), opt=True)
    _CellResourceReportListItem_dl_TotalofAvailablePRBs._const_val = ASN1Set(rv=[], rr=[ASN1RangeInt(lb=0, ub=100)], ev=None, er=[])
    _CellResourceReportListItem_ul_TotalofAvailablePRBs = INT(name='ul-TotalofAvailablePRBs', mode=MODE_TYPE, tag=(2, TAG_CONTEXT_SPEC, TAG_IMPLICIT), opt=True)
    _CellResourceReportListItem_ul_TotalofAvailablePRBs._const_val = ASN1Set(rv=[], rr=[ASN1RangeInt(lb=0, ub=100)], ev=None, er=[])
    _CellResourceReportListItem_servedPlmnPerCellList = SEQ_OF(name='servedPlmnPerCellList', mode=MODE_TYPE, tag=(3, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    __CellResourceReportListItem_servedPlmnPerCellList__item_ = SEQ(name='_item_', mode=MODE_TYPE, typeref=ASN1RefType(('E2SM-KPM-IEs', 'ServedPlmnPerCellListItem')))
    _CellResourceReportListItem_servedPlmnPerCellList._cont = __CellResourceReportListItem_servedPlmnPerCellList__item_
    _CellResourceReportListItem_servedPlmnPerCellList._const_sz = ASN1Set(rv=[], rr=[ASN1RangeInt(lb=1, ub=12)], ev=None, er=[])
    CellResourceReportListItem._cont = ASN1Dict([
        ('nRCGI', _CellResourceReportListItem_nRCGI),
        ('dl-TotalofAvailablePRBs', _CellResourceReportListItem_dl_TotalofAvailablePRBs),
        ('ul-TotalofAvailablePRBs', _CellResourceReportListItem_ul_TotalofAvailablePRBs),
        ('servedPlmnPerCellList', _CellResourceReportListItem_servedPlmnPerCellList),
        ])
    CellResourceReportListItem._ext = []
    
    #-----< ServedPlmnPerCellListItem >-----#
    ServedPlmnPerCellListItem = SEQ(name='ServedPlmnPerCellListItem', mode=MODE_TYPE)
    _ServedPlmnPerCellListItem_pLMN_Identity = OCT_STR(name='pLMN-Identity', mode=MODE_TYPE, tag=(0, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('E2SM-KPM-IEs', 'PLMN-Identity')))
    _ServedPlmnPerCellListItem_du_PM_5GC = SEQ(name='du-PM-5GC', mode=MODE_TYPE, tag=(1, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('E2SM-KPM-IEs', 'FGC-DU-PM-Container')), opt=True)
    _ServedPlmnPerCellListItem_du_PM_EPC = SEQ(name='du-PM-EPC', mode=MODE_TYPE, tag=(2, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('E2SM-KPM-IEs', 'EPC-DU-PM-Container')), opt=True)
    ServedPlmnPerCellListItem._cont = ASN1Dict([
        ('pLMN-Identity', _ServedPlmnPerCellListItem_pLMN_Identity),
        ('du-PM-5GC', _ServedPlmnPerCellListItem_du_PM_5GC),
        ('du-PM-EPC', _ServedPlmnPerCellListItem_du_PM_EPC),
        ])
    ServedPlmnPerCellListItem._ext = []
    
    #-----< FGC-DU-PM-Container >-----#
    FGC_DU_PM_Container = SEQ(name='FGC-DU-PM-Container', mode=MODE_TYPE)
    _FGC_DU_PM_Container_slicePerPlmnPerCellList = SEQ_OF(name='slicePerPlmnPerCellList', mode=MODE_TYPE, tag=(0, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    __FGC_DU_PM_Container_slicePerPlmnPerCellList__item_ = SEQ(name='_item_', mode=MODE_TYPE, typeref=ASN1RefType(('E2SM-KPM-IEs', 'SlicePerPlmnPerCellListItem')))
    _FGC_DU_PM_Container_slicePerPlmnPerCellList._cont = __FGC_DU_PM_Container_slicePerPlmnPerCellList__item_
    _FGC_DU_PM_Container_slicePerPlmnPerCellList._const_sz = ASN1Set(rv=[], rr=[ASN1RangeInt(lb=1, ub=1024)], ev=None, er=[])
    FGC_DU_PM_Container._cont = ASN1Dict([
        ('slicePerPlmnPerCellList', _FGC_DU_PM_Container_slicePerPlmnPerCellList),
        ])
    FGC_DU_PM_Container._ext = []
    
    #-----< SlicePerPlmnPerCellListItem >-----#
    SlicePerPlmnPerCellListItem = SEQ(name='SlicePerPlmnPerCellListItem', mode=MODE_TYPE)
    _SlicePerPlmnPerCellListItem_sliceID = SEQ(name='sliceID', mode=MODE_TYPE, tag=(0, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('E2SM-KPM-IEs', 'SNSSAI')))
    _SlicePerPlmnPerCellListItem_fQIPERSlicesPerPlmnPerCellList = SEQ_OF(name='fQIPERSlicesPerPlmnPerCellList', mode=MODE_TYPE, tag=(1, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    __SlicePerPlmnPerCellListItem_fQIPERSlicesPerPlmnPerCellList__item_ = SEQ(name='_item_', mode=MODE_TYPE, typeref=ASN1RefType(('E2SM-KPM-IEs', 'FQIPERSlicesPerPlmnPerCellListItem')))
    _SlicePerPlmnPerCellListItem_fQIPERSlicesPerPlmnPerCellList._cont = __SlicePerPlmnPerCellListItem_fQIPERSlicesPerPlmnPerCellList__item_
    _SlicePerPlmnPerCellListItem_fQIPERSlicesPerPlmnPerCellList._const_sz = ASN1Set(rv=[], rr=[ASN1RangeInt(lb=1, ub=64)], ev=None, er=[])
    SlicePerPlmnPerCellListItem._cont = ASN1Dict([
        ('sliceID', _SlicePerPlmnPerCellListItem_sliceID),
        ('fQIPERSlicesPerPlmnPerCellList', _SlicePerPlmnPerCellListItem_fQIPERSlicesPerPlmnPerCellList),
        ])
    SlicePerPlmnPerCellListItem._ext = []
    
    #-----< FQIPERSlicesPerPlmnPerCellListItem >-----#
    FQIPERSlicesPerPlmnPerCellListItem = SEQ(name='FQIPERSlicesPerPlmnPerCellListItem', mode=MODE_TYPE)
    _FQIPERSlicesPerPlmnPerCellListItem_fiveQI = INT(name='fiveQI', mode=MODE_TYPE, tag=(0, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    _FQIPERSlicesPerPlmnPerCellListItem_fiveQI._const_val = ASN1Set(rv=[], rr=[ASN1RangeInt(lb=0, ub=255)], ev=None, er=[])
    _FQIPERSlicesPerPlmnPerCellListItem_dl_PRBUsage = INT(name='dl-PRBUsage', mode=MODE_TYPE, tag=(1, TAG_CONTEXT_SPEC, TAG_IMPLICIT), opt=True)
    _FQIPERSlicesPerPlmnPerCellListItem_dl_PRBUsage._const_val = ASN1Set(rv=[], rr=[ASN1RangeInt(lb=0, ub=100)], ev=None, er=[])
    _FQIPERSlicesPerPlmnPerCellListItem_ul_PRBUsage = INT(name='ul-PRBUsage', mode=MODE_TYPE, tag=(2, TAG_CONTEXT_SPEC, TAG_IMPLICIT), opt=True)
    _FQIPERSlicesPerPlmnPerCellListItem_ul_PRBUsage._const_val = ASN1Set(rv=[], rr=[ASN1RangeInt(lb=0, ub=100)], ev=None, er=[])
    FQIPERSlicesPerPlmnPerCellListItem._cont = ASN1Dict([
        ('fiveQI', _FQIPERSlicesPerPlmnPerCellListItem_fiveQI),
        ('dl-PRBUsage', _FQIPERSlicesPerPlmnPerCellListItem_dl_PRBUsage),
        ('ul-PRBUsage', _FQIPERSlicesPerPlmnPerCellListItem_ul_PRBUsage),
        ])
    FQIPERSlicesPerPlmnPerCellListItem._ext = []
    
    #-----< EPC-DU-PM-Container >-----#
    EPC_DU_PM_Container = SEQ(name='EPC-DU-PM-Container', mode=MODE_TYPE)
    _EPC_DU_PM_Container_perQCIReportList = SEQ_OF(name='perQCIReportList', mode=MODE_TYPE, tag=(0, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    __EPC_DU_PM_Container_perQCIReportList__item_ = SEQ(name='_item_', mode=MODE_TYPE, typeref=ASN1RefType(('E2SM-KPM-IEs', 'PerQCIReportListItem')))
    _EPC_DU_PM_Container_perQCIReportList._cont = __EPC_DU_PM_Container_perQCIReportList__item_
    _EPC_DU_PM_Container_perQCIReportList._const_sz = ASN1Set(rv=[], rr=[ASN1RangeInt(lb=1, ub=256)], ev=None, er=[])
    EPC_DU_PM_Container._cont = ASN1Dict([
        ('perQCIReportList', _EPC_DU_PM_Container_perQCIReportList),
        ])
    EPC_DU_PM_Container._ext = []
    
    #-----< PerQCIReportListItem >-----#
    PerQCIReportListItem = SEQ(name='PerQCIReportListItem', mode=MODE_TYPE)
    _PerQCIReportListItem_qci = INT(name='qci', mode=MODE_TYPE, tag=(0, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    _PerQCIReportListItem_qci._const_val = ASN1Set(rv=[], rr=[ASN1RangeInt(lb=0, ub=255)], ev=None, er=[])
    _PerQCIReportListItem_dl_PRBUsage = INT(name='dl-PRBUsage', mode=MODE_TYPE, tag=(1, TAG_CONTEXT_SPEC, TAG_IMPLICIT), opt=True)
    _PerQCIReportListItem_dl_PRBUsage._const_val = ASN1Set(rv=[], rr=[ASN1RangeInt(lb=0, ub=100)], ev=None, er=[])
    _PerQCIReportListItem_ul_PRBUsage = INT(name='ul-PRBUsage', mode=MODE_TYPE, tag=(2, TAG_CONTEXT_SPEC, TAG_IMPLICIT), opt=True)
    _PerQCIReportListItem_ul_PRBUsage._const_val = ASN1Set(rv=[], rr=[ASN1RangeInt(lb=0, ub=100)], ev=None, er=[])
    PerQCIReportListItem._cont = ASN1Dict([
        ('qci', _PerQCIReportListItem_qci),
        ('dl-PRBUsage', _PerQCIReportListItem_dl_PRBUsage),
        ('ul-PRBUsage', _PerQCIReportListItem_ul_PRBUsage),
        ])
    PerQCIReportListItem._ext = []
    
    #-----< OCUCP-PF-Container >-----#
    OCUCP_PF_Container = SEQ(name='OCUCP-PF-Container', mode=MODE_TYPE)
    _OCUCP_PF_Container_gNB_CU_CP_Name = STR_PRINT(name='gNB-CU-CP-Name', mode=MODE_TYPE, tag=(0, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('E2SM-KPM-IEs', 'GNB-CU-CP-Name')), opt=True)
    _OCUCP_PF_Container_cu_CP_Resource_Status = SEQ(name='cu-CP-Resource-Status', mode=MODE_TYPE, tag=(1, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    __OCUCP_PF_Container_cu_CP_Resource_Status_numberOfActive_UEs = INT(name='numberOfActive-UEs', mode=MODE_TYPE, tag=(0, TAG_CONTEXT_SPEC, TAG_IMPLICIT), opt=True)
    __OCUCP_PF_Container_cu_CP_Resource_Status_numberOfActive_UEs._const_val = ASN1Set(rv=[], rr=[ASN1RangeInt(lb=1, ub=65536)], ev=[], er=[])
    _OCUCP_PF_Container_cu_CP_Resource_Status._cont = ASN1Dict([
        ('numberOfActive-UEs', __OCUCP_PF_Container_cu_CP_Resource_Status_numberOfActive_UEs),
        ])
    _OCUCP_PF_Container_cu_CP_Resource_Status._ext = None
    OCUCP_PF_Container._cont = ASN1Dict([
        ('gNB-CU-CP-Name', _OCUCP_PF_Container_gNB_CU_CP_Name),
        ('cu-CP-Resource-Status', _OCUCP_PF_Container_cu_CP_Resource_Status),
        ])
    OCUCP_PF_Container._ext = None
    
    #-----< OCUUP-PF-Container >-----#
    OCUUP_PF_Container = SEQ(name='OCUUP-PF-Container', mode=MODE_TYPE)
    _OCUUP_PF_Container_gNB_CU_UP_Name = STR_PRINT(name='gNB-CU-UP-Name', mode=MODE_TYPE, tag=(0, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('E2SM-KPM-IEs', 'GNB-CU-UP-Name')), opt=True)
    _OCUUP_PF_Container_pf_ContainerList = SEQ_OF(name='pf-ContainerList', mode=MODE_TYPE, tag=(1, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    __OCUUP_PF_Container_pf_ContainerList__item_ = SEQ(name='_item_', mode=MODE_TYPE, typeref=ASN1RefType(('E2SM-KPM-IEs', 'PF-ContainerListItem')))
    _OCUUP_PF_Container_pf_ContainerList._cont = __OCUUP_PF_Container_pf_ContainerList__item_
    _OCUUP_PF_Container_pf_ContainerList._const_sz = ASN1Set(rv=[], rr=[ASN1RangeInt(lb=1, ub=3)], ev=None, er=[])
    OCUUP_PF_Container._cont = ASN1Dict([
        ('gNB-CU-UP-Name', _OCUUP_PF_Container_gNB_CU_UP_Name),
        ('pf-ContainerList', _OCUUP_PF_Container_pf_ContainerList),
        ])
    OCUUP_PF_Container._ext = []
    
    #-----< PF-ContainerListItem >-----#
    PF_ContainerListItem = SEQ(name='PF-ContainerListItem', mode=MODE_TYPE)
    _PF_ContainerListItem_interface_type = ENUM(name='interface-type', mode=MODE_TYPE, tag=(0, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('E2SM-KPM-IEs', 'NI-Type')))
    _PF_ContainerListItem_o_CU_UP_PM_Container = SEQ(name='o-CU-UP-PM-Container', mode=MODE_TYPE, tag=(1, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('E2SM-KPM-IEs', 'CUUPMeasurement-Container')))
    PF_ContainerListItem._cont = ASN1Dict([
        ('interface-type', _PF_ContainerListItem_interface_type),
        ('o-CU-UP-PM-Container', _PF_ContainerListItem_o_CU_UP_PM_Container),
        ])
    PF_ContainerListItem._ext = []
    
    #-----< CUUPMeasurement-Container >-----#
    CUUPMeasurement_Container = SEQ(name='CUUPMeasurement-Container', mode=MODE_TYPE)
    _CUUPMeasurement_Container_plmnList = SEQ_OF(name='plmnList', mode=MODE_TYPE, tag=(0, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    __CUUPMeasurement_Container_plmnList__item_ = SEQ(name='_item_', mode=MODE_TYPE, typeref=ASN1RefType(('E2SM-KPM-IEs', 'PlmnID-List')))
    _CUUPMeasurement_Container_plmnList._cont = __CUUPMeasurement_Container_plmnList__item_
    _CUUPMeasurement_Container_plmnList._const_sz = ASN1Set(rv=[], rr=[ASN1RangeInt(lb=1, ub=12)], ev=None, er=[])
    CUUPMeasurement_Container._cont = ASN1Dict([
        ('plmnList', _CUUPMeasurement_Container_plmnList),
        ])
    CUUPMeasurement_Container._ext = []
    
    #-----< PlmnID-List >-----#
    PlmnID_List = SEQ(name='PlmnID-List', mode=MODE_TYPE)
    _PlmnID_List_pLMN_Identity = OCT_STR(name='pLMN-Identity', mode=MODE_TYPE, tag=(0, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('E2SM-KPM-IEs', 'PLMN-Identity')))
    _PlmnID_List_cu_UP_PM_5GC = SEQ(name='cu-UP-PM-5GC', mode=MODE_TYPE, tag=(1, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('E2SM-KPM-IEs', 'FGC-CUUP-PM-Format')), opt=True)
    _PlmnID_List_cu_UP_PM_EPC = SEQ(name='cu-UP-PM-EPC', mode=MODE_TYPE, tag=(2, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('E2SM-KPM-IEs', 'EPC-CUUP-PM-Format')), opt=True)
    PlmnID_List._cont = ASN1Dict([
        ('pLMN-Identity', _PlmnID_List_pLMN_Identity),
        ('cu-UP-PM-5GC', _PlmnID_List_cu_UP_PM_5GC),
        ('cu-UP-PM-EPC', _PlmnID_List_cu_UP_PM_EPC),
        ])
    PlmnID_List._ext = []
    
    #-----< FGC-CUUP-PM-Format >-----#
    FGC_CUUP_PM_Format = SEQ(name='FGC-CUUP-PM-Format', mode=MODE_TYPE)
    _FGC_CUUP_PM_Format_sliceToReportList = SEQ_OF(name='sliceToReportList', mode=MODE_TYPE, tag=(0, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    __FGC_CUUP_PM_Format_sliceToReportList__item_ = SEQ(name='_item_', mode=MODE_TYPE, typeref=ASN1RefType(('E2SM-KPM-IEs', 'SliceToReportListItem')))
    _FGC_CUUP_PM_Format_sliceToReportList._cont = __FGC_CUUP_PM_Format_sliceToReportList__item_
    _FGC_CUUP_PM_Format_sliceToReportList._const_sz = ASN1Set(rv=[], rr=[ASN1RangeInt(lb=1, ub=1024)], ev=None, er=[])
    FGC_CUUP_PM_Format._cont = ASN1Dict([
        ('sliceToReportList', _FGC_CUUP_PM_Format_sliceToReportList),
        ])
    FGC_CUUP_PM_Format._ext = []
    
    #-----< SliceToReportListItem >-----#
    SliceToReportListItem = SEQ(name='SliceToReportListItem', mode=MODE_TYPE)
    _SliceToReportListItem_sliceID = SEQ(name='sliceID', mode=MODE_TYPE, tag=(0, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('E2SM-KPM-IEs', 'SNSSAI')))
    _SliceToReportListItem_fQIPERSlicesPerPlmnList = SEQ_OF(name='fQIPERSlicesPerPlmnList', mode=MODE_TYPE, tag=(1, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    __SliceToReportListItem_fQIPERSlicesPerPlmnList__item_ = SEQ(name='_item_', mode=MODE_TYPE, typeref=ASN1RefType(('E2SM-KPM-IEs', 'FQIPERSlicesPerPlmnListItem')))
    _SliceToReportListItem_fQIPERSlicesPerPlmnList._cont = __SliceToReportListItem_fQIPERSlicesPerPlmnList__item_
    _SliceToReportListItem_fQIPERSlicesPerPlmnList._const_sz = ASN1Set(rv=[], rr=[ASN1RangeInt(lb=1, ub=64)], ev=None, er=[])
    SliceToReportListItem._cont = ASN1Dict([
        ('sliceID', _SliceToReportListItem_sliceID),
        ('fQIPERSlicesPerPlmnList', _SliceToReportListItem_fQIPERSlicesPerPlmnList),
        ])
    SliceToReportListItem._ext = []
    
    #-----< FQIPERSlicesPerPlmnListItem >-----#
    FQIPERSlicesPerPlmnListItem = SEQ(name='FQIPERSlicesPerPlmnListItem', mode=MODE_TYPE)
    _FQIPERSlicesPerPlmnListItem_fiveQI = INT(name='fiveQI', mode=MODE_TYPE, tag=(0, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    _FQIPERSlicesPerPlmnListItem_fiveQI._const_val = ASN1Set(rv=[], rr=[ASN1RangeInt(lb=0, ub=255)], ev=None, er=[])
    _FQIPERSlicesPerPlmnListItem_pDCPBytesDL = INT(name='pDCPBytesDL', mode=MODE_TYPE, tag=(1, TAG_CONTEXT_SPEC, TAG_IMPLICIT), opt=True)
    _FQIPERSlicesPerPlmnListItem_pDCPBytesDL._const_val = ASN1Set(rv=[], rr=[ASN1RangeInt(lb=0, ub=10000000000)], ev=[], er=[])
    _FQIPERSlicesPerPlmnListItem_pDCPBytesUL = INT(name='pDCPBytesUL', mode=MODE_TYPE, tag=(2, TAG_CONTEXT_SPEC, TAG_IMPLICIT), opt=True)
    _FQIPERSlicesPerPlmnListItem_pDCPBytesUL._const_val = ASN1Set(rv=[], rr=[ASN1RangeInt(lb=0, ub=10000000000)], ev=[], er=[])
    FQIPERSlicesPerPlmnListItem._cont = ASN1Dict([
        ('fiveQI', _FQIPERSlicesPerPlmnListItem_fiveQI),
        ('pDCPBytesDL', _FQIPERSlicesPerPlmnListItem_pDCPBytesDL),
        ('pDCPBytesUL', _FQIPERSlicesPerPlmnListItem_pDCPBytesUL),
        ])
    FQIPERSlicesPerPlmnListItem._ext = []
    
    #-----< EPC-CUUP-PM-Format >-----#
    EPC_CUUP_PM_Format = SEQ(name='EPC-CUUP-PM-Format', mode=MODE_TYPE)
    _EPC_CUUP_PM_Format_perQCIReportList = SEQ_OF(name='perQCIReportList', mode=MODE_TYPE, tag=(0, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    __EPC_CUUP_PM_Format_perQCIReportList__item_ = SEQ(name='_item_', mode=MODE_TYPE, typeref=ASN1RefType(('E2SM-KPM-IEs', 'PerQCIReportListItemFormat')))
    _EPC_CUUP_PM_Format_perQCIReportList._cont = __EPC_CUUP_PM_Format_perQCIReportList__item_
    _EPC_CUUP_PM_Format_perQCIReportList._const_sz = ASN1Set(rv=[], rr=[ASN1RangeInt(lb=1, ub=256)], ev=None, er=[])
    EPC_CUUP_PM_Format._cont = ASN1Dict([
        ('perQCIReportList', _EPC_CUUP_PM_Format_perQCIReportList),
        ])
    EPC_CUUP_PM_Format._ext = []
    
    #-----< PerQCIReportListItemFormat >-----#
    PerQCIReportListItemFormat = SEQ(name='PerQCIReportListItemFormat', mode=MODE_TYPE)
    _PerQCIReportListItemFormat_qci = INT(name='qci', mode=MODE_TYPE, tag=(0, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    _PerQCIReportListItemFormat_qci._const_val = ASN1Set(rv=[], rr=[ASN1RangeInt(lb=0, ub=255)], ev=None, er=[])
    _PerQCIReportListItemFormat_pDCPBytesDL = INT(name='pDCPBytesDL', mode=MODE_TYPE, tag=(1, TAG_CONTEXT_SPEC, TAG_IMPLICIT), opt=True)
    _PerQCIReportListItemFormat_pDCPBytesDL._const_val = ASN1Set(rv=[], rr=[ASN1RangeInt(lb=0, ub=10000000000)], ev=[], er=[])
    _PerQCIReportListItemFormat_pDCPBytesUL = INT(name='pDCPBytesUL', mode=MODE_TYPE, tag=(2, TAG_CONTEXT_SPEC, TAG_IMPLICIT), opt=True)
    _PerQCIReportListItemFormat_pDCPBytesUL._const_val = ASN1Set(rv=[], rr=[ASN1RangeInt(lb=0, ub=10000000000)], ev=[], er=[])
    PerQCIReportListItemFormat._cont = ASN1Dict([
        ('qci', _PerQCIReportListItemFormat_qci),
        ('pDCPBytesDL', _PerQCIReportListItemFormat_pDCPBytesDL),
        ('pDCPBytesUL', _PerQCIReportListItemFormat_pDCPBytesUL),
        ])
    PerQCIReportListItemFormat._ext = []
    
    _all_ = [
        _GlobalKPMnode_ID_gNB,
        _GlobalKPMnode_ID_en_gNB,
        _GlobalKPMnode_ID_ng_eNB,
        _GlobalKPMnode_ID_eNB,
        GlobalKPMnode_ID,
        _GlobalKPMnode_gNB_ID_global_gNB_ID,
        _GlobalKPMnode_gNB_ID_gNB_CU_UP_ID,
        _GlobalKPMnode_gNB_ID_gNB_DU_ID,
        GlobalKPMnode_gNB_ID,
        _GlobalgNB_ID_plmn_id,
        _GlobalgNB_ID_gnb_id,
        GlobalgNB_ID,
        GNB_CU_UP_ID,
        GNB_DU_ID,
        _GNB_ID_Choice_gnb_ID,
        GNB_ID_Choice,
        _GlobalKPMnode_en_gNB_ID_global_gNB_ID,
        GlobalKPMnode_en_gNB_ID,
        _GlobalenGNB_ID_pLMN_Identity,
        _GlobalenGNB_ID_gNB_ID,
        GlobalenGNB_ID,
        _ENGNB_ID_gNB_ID,
        ENGNB_ID,
        _GlobalKPMnode_ng_eNB_ID_global_ng_eNB_ID,
        GlobalKPMnode_ng_eNB_ID,
        _GlobalngeNB_ID_plmn_id,
        _GlobalngeNB_ID_enb_id,
        GlobalngeNB_ID,
        _ENB_ID_Choice_enb_ID_macro,
        _ENB_ID_Choice_enb_ID_shortmacro,
        _ENB_ID_Choice_enb_ID_longmacro,
        ENB_ID_Choice,
        _GlobalKPMnode_eNB_ID_global_eNB_ID,
        GlobalKPMnode_eNB_ID,
        _GlobalENB_ID_pLMN_Identity,
        _GlobalENB_ID_eNB_ID,
        GlobalENB_ID,
        _ENB_ID_macro_eNB_ID,
        _ENB_ID_home_eNB_ID,
        _ENB_ID_short_Macro_eNB_ID,
        _ENB_ID_long_Macro_eNB_ID,
        ENB_ID,
        _NRCGI_pLMN_Identity,
        _NRCGI_nRCellIdentity,
        NRCGI,
        PLMN_Identity,
        NRCellIdentity,
        _SNSSAI_sST,
        _SNSSAI_sD,
        SNSSAI,
        maxofMessageProtocolTests,
        maxofRICstyles,
        maxnoofQCI,
        maxnoofQoSFlows,
        maxnoofSliceItems,
        maxnoofContainerListItems,
        maxCellingNBDU,
        maxofContainers,
        maxPLMN,
        RIC_Style_Type,
        RIC_Style_Name,
        RIC_Format_Type,
        _E2SM_KPM_EventTriggerDefinition_eventDefinition_Format1,
        E2SM_KPM_EventTriggerDefinition,
        __E2SM_KPM_EventTriggerDefinition_Format1_policyTest_List__item_,
        _E2SM_KPM_EventTriggerDefinition_Format1_policyTest_List,
        E2SM_KPM_EventTriggerDefinition_Format1,
        _E2SM_KPM_ActionDefinition_ric_Style_Type,
        E2SM_KPM_ActionDefinition,
        _E2SM_KPM_IndicationHeader_indicationHeader_Format1,
        E2SM_KPM_IndicationHeader,
        _E2SM_KPM_IndicationHeader_Format1_id_GlobalKPMnode_ID,
        _E2SM_KPM_IndicationHeader_Format1_nRCGI,
        _E2SM_KPM_IndicationHeader_Format1_pLMN_Identity,
        _E2SM_KPM_IndicationHeader_Format1_sliceID,
        _E2SM_KPM_IndicationHeader_Format1_fiveQI,
        _E2SM_KPM_IndicationHeader_Format1_qci,
        E2SM_KPM_IndicationHeader_Format1,
        _E2SM_KPM_IndicationMessage_ric_Style_Type,
        _E2SM_KPM_IndicationMessage_indicationMessage_Format1,
        E2SM_KPM_IndicationMessage,
        __E2SM_KPM_IndicationMessage_Format1_pm_Containers__item_,
        _E2SM_KPM_IndicationMessage_Format1_pm_Containers,
        E2SM_KPM_IndicationMessage_Format1,
        _PM_Containers_List_performanceContainer,
        _PM_Containers_List_theRANContainer,
        PM_Containers_List,
        _E2SM_KPM_RANfunction_Description_ranFunction_Name,
        ___E2SM_KPM_RANfunction_Description_e2SM_KPM_RANfunction_Item_ric_EventTriggerStyle_List__item_,
        __E2SM_KPM_RANfunction_Description_e2SM_KPM_RANfunction_Item_ric_EventTriggerStyle_List,
        ___E2SM_KPM_RANfunction_Description_e2SM_KPM_RANfunction_Item_ric_ReportStyle_List__item_,
        __E2SM_KPM_RANfunction_Description_e2SM_KPM_RANfunction_Item_ric_ReportStyle_List,
        _E2SM_KPM_RANfunction_Description_e2SM_KPM_RANfunction_Item,
        E2SM_KPM_RANfunction_Description,
        NI_Type,
        RAN_Container,
        _Trigger_ConditionIE_Item_report_Period_IE,
        Trigger_ConditionIE_Item,
        RT_Period_IE,
        RANcallProcess_ID_string,
        _RANfunction_Name_ranFunction_ShortName,
        _RANfunction_Name_ranFunction_E2SM_OID,
        _RANfunction_Name_ranFunction_Description,
        _RANfunction_Name_ranFunction_Instance,
        RANfunction_Name,
        _RIC_EventTriggerStyle_List_ric_EventTriggerStyle_Type,
        _RIC_EventTriggerStyle_List_ric_EventTriggerStyle_Name,
        _RIC_EventTriggerStyle_List_ric_EventTriggerFormat_Type,
        RIC_EventTriggerStyle_List,
        _RIC_ReportStyle_List_ric_ReportStyle_Type,
        _RIC_ReportStyle_List_ric_ReportStyle_Name,
        _RIC_ReportStyle_List_ric_IndicationHeaderFormat_Type,
        _RIC_ReportStyle_List_ric_IndicationMessageFormat_Type,
        RIC_ReportStyle_List,
        _PF_Container_oDU,
        _PF_Container_oCU_CP,
        _PF_Container_oCU_UP,
        PF_Container,
        GNB_CU_CP_Name,
        GNB_DU_Name,
        GNB_CU_UP_Name,
        __ODU_PF_Container_cellResourceReportList__item_,
        _ODU_PF_Container_cellResourceReportList,
        ODU_PF_Container,
        _CellResourceReportListItem_nRCGI,
        _CellResourceReportListItem_dl_TotalofAvailablePRBs,
        _CellResourceReportListItem_ul_TotalofAvailablePRBs,
        __CellResourceReportListItem_servedPlmnPerCellList__item_,
        _CellResourceReportListItem_servedPlmnPerCellList,
        CellResourceReportListItem,
        _ServedPlmnPerCellListItem_pLMN_Identity,
        _ServedPlmnPerCellListItem_du_PM_5GC,
        _ServedPlmnPerCellListItem_du_PM_EPC,
        ServedPlmnPerCellListItem,
        __FGC_DU_PM_Container_slicePerPlmnPerCellList__item_,
        _FGC_DU_PM_Container_slicePerPlmnPerCellList,
        FGC_DU_PM_Container,
        _SlicePerPlmnPerCellListItem_sliceID,
        __SlicePerPlmnPerCellListItem_fQIPERSlicesPerPlmnPerCellList__item_,
        _SlicePerPlmnPerCellListItem_fQIPERSlicesPerPlmnPerCellList,
        SlicePerPlmnPerCellListItem,
        _FQIPERSlicesPerPlmnPerCellListItem_fiveQI,
        _FQIPERSlicesPerPlmnPerCellListItem_dl_PRBUsage,
        _FQIPERSlicesPerPlmnPerCellListItem_ul_PRBUsage,
        FQIPERSlicesPerPlmnPerCellListItem,
        __EPC_DU_PM_Container_perQCIReportList__item_,
        _EPC_DU_PM_Container_perQCIReportList,
        EPC_DU_PM_Container,
        _PerQCIReportListItem_qci,
        _PerQCIReportListItem_dl_PRBUsage,
        _PerQCIReportListItem_ul_PRBUsage,
        PerQCIReportListItem,
        _OCUCP_PF_Container_gNB_CU_CP_Name,
        __OCUCP_PF_Container_cu_CP_Resource_Status_numberOfActive_UEs,
        _OCUCP_PF_Container_cu_CP_Resource_Status,
        OCUCP_PF_Container,
        _OCUUP_PF_Container_gNB_CU_UP_Name,
        __OCUUP_PF_Container_pf_ContainerList__item_,
        _OCUUP_PF_Container_pf_ContainerList,
        OCUUP_PF_Container,
        _PF_ContainerListItem_interface_type,
        _PF_ContainerListItem_o_CU_UP_PM_Container,
        PF_ContainerListItem,
        __CUUPMeasurement_Container_plmnList__item_,
        _CUUPMeasurement_Container_plmnList,
        CUUPMeasurement_Container,
        _PlmnID_List_pLMN_Identity,
        _PlmnID_List_cu_UP_PM_5GC,
        _PlmnID_List_cu_UP_PM_EPC,
        PlmnID_List,
        __FGC_CUUP_PM_Format_sliceToReportList__item_,
        _FGC_CUUP_PM_Format_sliceToReportList,
        FGC_CUUP_PM_Format,
        _SliceToReportListItem_sliceID,
        __SliceToReportListItem_fQIPERSlicesPerPlmnList__item_,
        _SliceToReportListItem_fQIPERSlicesPerPlmnList,
        SliceToReportListItem,
        _FQIPERSlicesPerPlmnListItem_fiveQI,
        _FQIPERSlicesPerPlmnListItem_pDCPBytesDL,
        _FQIPERSlicesPerPlmnListItem_pDCPBytesUL,
        FQIPERSlicesPerPlmnListItem,
        __EPC_CUUP_PM_Format_perQCIReportList__item_,
        _EPC_CUUP_PM_Format_perQCIReportList,
        EPC_CUUP_PM_Format,
        _PerQCIReportListItemFormat_qci,
        _PerQCIReportListItemFormat_pDCPBytesDL,
        _PerQCIReportListItemFormat_pDCPBytesUL,
        PerQCIReportListItemFormat,
    ]

init_modules(E2SM_KPM_IEs)
