apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rl-models-pvc
  namespace: ricxapp
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  # Uncomment and set if your cluster does not have a default StorageClass.
  # storageClassName: standard
